package protocol

const (
	MAX_HEADER_STR_LENGTH    = 255
	MAX_SOCKS_TCP_HEADER_LEN = 7 + MAX_HEADER_STR_LENGTH
	MAX_SOCKS_UDP_HEADER_LEN = 7 + MAX_HEADER_STR_LENGTH
	GOST_UDP_FRAG_FLAG       = 255
	MAX_AUTH_METHODS_COUNT   = 255
)
